services:
  via-bridge-frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_NETWORK=testnet
    volumes:
      # Mount source code for development (optional - remove for production)
      - ./src:/app/src:ro
      - ./public:/app/public:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development database or other services here
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: via_bridge
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: devpass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: